# Generated by Django 6.1 on 2026-08-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal label, e.g. 'Factory floor wide shot'",
                        max_length=150,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("hero", "Hero / Top of Page"),
                            ("story", "Our Story"),
                            ("credentials", "Company Credentials"),
                            ("quality_control", "Quality Control"),
                            ("welfare", "Employee Welfare"),
                            ("general", "General / Unassigned"),
                        ],
                        default="general",
                        help_text="Which part of the About page this image should appear in.",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="about/")),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional alt text / caption shown on the site.",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first within a section.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide without deleting."
                    ),
                ),
            ],
            options={
                "verbose_name": "About Page Image",
                "verbose_name_plural": "About Page Images",
                "ordering": ["section", "order", "-id"],
            },
        ),
    ]
